### ISSUE TITLE
Grid_China_Map

### ISSUE THREAD

**Issue by weiyunna** [hafen/geofacet#57]
this is China Grid Map

Grid data:

```
"code","name","row","col"
"HL","Heilongjiang",1,10
"NM","Innermogolia",2,7
"JL","Jilin",2,10
"XJ","Xinjiang",2,1
"BJ","Beijing",3,8
"LN","Liaoning",3,9
"NX","Ningxia",3,5
"TJ","Tianjin",4,8
"HE","Hebei",4,7
"QH","Qinghai",4,2
"HA","Henan",5,7
"SX","Shanxi",5,6
"SD","Shandong",5,8
"GS","Gansu",5,4
"HB","Hubei",6,6
"AH","Anhui",6,7
"SH","Shanghai",6,9
"SN","Shaanxi",6,5
"JS","Jiangsu",6,8
"HN","Hunan",7,6
"CQ","Chongqing",7,5
"ZJ","Zhejiang",7,8
"XZ","Xizang",7,2
"TW","Taiwan",8,10
"SC","Sichuan",7,4
"JX","Jiangxi",8,7
"GZ","Guizhou",8,5
"FJ","Fujian",8,8
"YN","Yunnan",9,4
"GX","Guangxi",9,6
"GD","Guangdong",9,7
"MC","Macau",10,9
"HK","Hongkong",10,10
"HI","Hainan",11,7
```

**Comment by lijianguo531** [comment]
is it accepted in github?

**Comment by hafen** [comment]
I've been away. I'll merge this into the package in the next few days.

**Comment by lijianguo531** [comment]
That's great！Thank you very much！

**Comment by hafen** [comment]
Adding a reference image for the grid database (let me know if it's not accurate):

![image](https://user-images.githubusercontent.com/1275592/30039720-cf9c8532-9189-11e7-856b-a6ecf449ee0c.png)

**Comment by hafen** [comment]
Thanks! Added as `china_prov_grid1`.

**Comment by lijianguo531** [comment]
Taiwan should be added into the China map.

**Comment by lijianguo531** [comment]
Today, I check the grid names in geofacet package, however, I do not find china_prov_grid1 you added.

**Comment by hafen** [comment]
@lijianguo531 sorry about that I just grabbed a map I found online without much thought. If you can provide a map reference image that looks good that would be great.

The grid is in the package. In short, you need to reinstall the package from github to get the new grid. In theory you shouldn't need to reinstall and it would still find the grid and grab it from the web (but the grid wouldn't show up in `get_grid_names()` since that only checks locally-installed grids) but there is a bug in that code that I have fixed and need to submit to CRAN.
