### ISSUE TITLE
new grid: 'london_boroughs_grid'

### ISSUE THREAD

**Issue by eldenvo** [hafen/geofacet#7]
Geofacet grid for the 32 Boroughs of London, UK, plus The City of London. Inspired by this London Squared Map: http://aftertheflood.co/projects/london-squared-map

Rather than use the ISO_3166-2 codes, which are available for London (https://en.wikipedia.org/wiki/ISO_3166-2:GB), I have used the ONS (Office of National Statistics) geocodes which are very commonly uses with statistics in the UK (see here: http://geoportal.statistics.gov.uk/datasets/464be6191a434a91a5fa2f52c7433333_0?uiTab=table)
Obviously you could use the ISO codes but to my knowledge they're not frequently used or well known.

![london-boroughs-map](https://cloud.githubusercontent.com/assets/13021448/26399784/3133d684-4076-11e7-8eac-1e74d023bf18.jpg)

Grid data:

```
"code","row","col","name"
"E09000001",4,5,"City of London"
"E09000002",4,8,"Barking and Dagenham"
"E09000003",2,4,"Barnet"
"E09000004",5,8,"Bexley"
"E09000005",3,3,"Brent"
"E09000006",6,6,"Bromley"
"E09000007",3,4,"Camden"
"E09000008",6,5,"Croydon"
"E09000009",3,2,"Ealing"
"E09000010",1,5,"Enfield"
"E09000011",5,7,"Greenwich"
"E09000012",3,6,"Hackney"
"E09000013",4,2,"Hammersmith and Fulham"
"E09000014",2,5,"Haringey"
"E09000015",2,3,"Harrow"
"E09000016",3,8,"Havering"
"E09000017",3,1,"Hillingdon"
"E09000018",4,1,"Hounslow"
"E09000019",3,5,"Islington"
"E09000020",4,3,"Kensington and Chelsea"
"E09000021",5,2,"Kingston upon Thames"
"E09000022",5,4,"Lambeth"
"E09000023",5,6,"Lewisham"
"E09000024",6,4,"Merton"
"E09000025",4,7,"Newham"
"E09000026",3,7,"Redbridge"
"E09000027",6,3,"Richmond upon Thames"
"E09000028",5,5,"Southwark"
"E09000029",7,4,"Sutton"
"E09000030",4,6,"Tower Hamlets"
"E09000031",2,6,"Waltham Forest"
"E09000032",5,3,"Wandsworth"
"E09000033",4,4,"Westminster"
```

Example code to produce the plot below here: https://gist.github.com/eldenvo/f98d1adee22e9987b0cc97c117a619db#file-london_boroughs_geofacet_example-r

![tester](https://cloud.githubusercontent.com/assets/13021448/26407717/cac158a4-4093-11e7-9ad7-390afb13e857.png)

**Comment by hafen** [comment]
Nice! I'll add this in.

This brings up a good question about codes. I don't know enough about which codes are most popular at different levels and whether this changes geographically, so it's good to get this perspective. I'm thinking we could start to err on the side of providing multiple columns of candidate codes. What the package currently does is it checks your faceting variable against the grid and matches with the grid's name or code depending on which matches best. I could extend that so that it checks all columns in the grid and chooses the one that matches best. This way multiple codes can be in a grid and therefore the grids can work more flexibly with different data sources without requiring a lot of painful refactoring of the data prior to plotting. What do you think? @jonmcalder, curious of your opinion too as this came up with your grid as well.

**Comment by jonmcalder** [comment]
I also don't have a good sense of how these codes change over different geographical regions, but as Alex has noted here in the case of London/UK (and in my opinion this is also true of South Africa) it may often occur that the ISO codes are not the commonly used or well known abbreviations for provincial/state/region codes.

This may just mean using different codes for display purposes than are used for joining purposes?

**Comment by hafen** [comment]
Yeah I think I'll relax the constraints on a grid such that it needs `row` and `col` variables and then variables that begin with `code` and `name`. This way you could have `code_iso2`, `code_abb`, etc. and `name_en`, `name_af`, etc., giving more options to match against and more options to use as labels. Although maybe it's better to keep it simple and consistent.

**Comment by eldenvo** [comment]
I think that's a good solution. From my experience, geo-data in the UK comes with an ONS code (like those above), a name, and a Welsh name (where appropriate). It will often be that the names don't match (& vs 'and' etc)

**Comment by hafen** [comment]
Sounds good. I merged this grid in. Thanks!

I also made some internal changes so that now you can specify a grid with multiple `code` and `name`columns and you can specify which of these columns should be used as your panel labels with a `label` argument added to `facet_geo()`.

For example, I took the South African grid and added in @jonmcalder's original codes as `code_abb`, and I also added a column `name_af` for the Afrikaans name of each province. Now you can do this:

```r
ggplot(sa_pop_dens, aes(factor(year), density, fill = factor(year))) +
  geom_col() +
  facet_geo(~ code, grid = "sa_prov_grid1", label = "name_af") +
  labs(title = "South Africa population density by province",
    caption = "Data Source: Statistics SA Census",
    y = "Population density per square km") +
  theme_bw()
```

Even though you are faceting on the `code` column of the input data, it will find the right code in the grid to match with and then use the corresponding `name_af` values in the panel labels. The idea of this is to save effort on the part of the analyst, where their data will probably usually have codes instead of names. This will help also avoid the issue of names sometimes being slightly different, as noted by @eldenvo. You also might imagine adding name columns to your grids such as `name_short` that contains an abbreviated name to possibly use as labels.

**Comment by jonmcalder** [comment]
Ok cool - this seems like a neat (and flexible) approach to me. Nicely done!

**Comment by hafen** [comment]
Thanks!
