### ISSUE TITLE
Feature idea: create grid from centroids of shapes

### ISSUE THREAD

**Issue by mavelli** [hafen/geofacet#72]
I just came across your great work and like the idea. Since i create usually maps based on spdf objects and then just use the centroids to show a number or symbol, i was wondering if you are intending to enhance your geofacet to accept centroids or just spatial points to create a grid based on that. 
I didnt yet look too deep in your code and as a workaround was thinking that creating a sparse grid for geofacet would work. what do you think?

**Comment by hafen** [comment]
If someone can write an algorithm that will turn centroids into a grid, I would be be more than happy to incorporate that into this package. It's harder than it sounds though. You want a very dense grid so as to maximize use of the space of the plot, but you also want to preserve grid neighbors, etc. I'd argue that there are several cases where a good grid is not possible. Note that this package is only meant for a regular grid where each item in the grid is the same size, which is necessary for meaningful visual comparisons. If you have any ideas here, I that would be great!

**Comment by johnjosephhorton** [comment]
I was looking for the same thing - here's my attempt: 
http://john-joseph-horton.com/extending-geofacet-to-algorithmically-generate-grids-from-lat-long-data/
I forked the repo. I'm not a competent enough R programmer to suggest anyone just pull in my changes (even if they look worthwhile). Here's the link to my fork: 
https://github.com/johnjosephhorton/geofacet

**Comment by hafen** [comment]
Support for this has been added using the geogrid package (see the examples [here](https://github.com/hafen/geofacet/blob/master/R/grid_auto.R).

@johnjosephhorton it would be interesting to compare to your approach and maybe provide that as an option, but I haven't had time to do the comparison and integration. I'm going to mark this as closed for now since functionality is there but feel free to open if it warrants more discussion.
